const movies = [
    {
      "Title": "Patton Oswalt: Annihilation",
      "fulltitle": "Patton Oswalt: Annihilation (2017)",
      "movie_year": 2017,
      "Categories": "Uncategorized",
      "summary": "Patton Oswald, despite a personal tragedy, produces his best standup yet.",
      "ImageURL": "https://www.example.com/images/dinosaur.jpg",
      "imdb_id": "tt7026230",
      "imdb_rating": 7.4,
      "runtime": 66,
      "language": "English",
      "ytid": "4hZi5QaMBFc"
    },
    {
      "Title": "New York Doll",
      "fulltitle": "New York Doll (2005)",
      "movie_year": 2005,
      "Categories": "Documentary|Music",
      "summary": "A recovering alcoholic and recently converted Mormon, Arthur \"Killer\" Kane, of the rock band The New York Dolls, is given a chance at reuniting with his band after 30 years.",
      "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/New-York-Doll-Movie-Poster.jpg",
      "imdb_id": "tt0436629",
      "imdb_rating": 7.9,
      "runtime": 75,
      "language": "English",
      "ytid": "jwD04NsnLLg"
    },
    {
      "Title": "Mickey's Magical Christmas: Snowed in at the House of Mouse",
      "fulltitle": "Mickey's Magical Christmas: Snowed in at the House of Mouse (2001)",
      "movie_year": 2001,
      "Categories": "Adventure|Animation|Comedy|Family|Fantasy",
      "summary": "After everyone is snowed in at the House of Mouse, Mickey suggests they throw their own Christmas party.",
      "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/Mickeys-Magical-Christmas-Snowed-in-at-the-House-of-Mouse-Movie-Poster.jpg",
      "imdb_id": "tt0300195",
      "imdb_rating": 6.8,
      "runtime": 65,
      "language": "English",
      "ytid": "uCKwHHftrU4"
    },
    {
      "Title": "Mickey's House of Villains",
      "fulltitle": "Mickey's House of Villains (2001)",
      "movie_year": 2001,
      "Categories": "Animation|Comedy|Family|Fantasy|Horror",
      "summary": "The villains from the popular animated Disney films are gathered at the House of Mouse with plans to take over.",
      "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/Mickeys-House-of-Villains-Movie-Poster.jpg",
      "imdb_id": "tt0329374",
      "imdb_rating": 6.6,
      "runtime": 0,
      "language": "English",
      "ytid": "JA03ciYt-Ek"
    },
    {
      "Title": "And Then I Go",
      "fulltitle": "And Then I Go (2017)",
      "movie_year": 2017,
      "Categories": "Drama",
      "summary": "In the cruel world of junior high, Edwin suffers in a state of anxiety and alienation alongside his only friend.",
      "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/And-Then-I-Go-Movie-Poster.jpg",
      "imdb_id": "tt2018111",
      "imdb_rating": 7.6,
      "runtime": 99,
      "language": "English",
      "ytid": "8CdIiD6-iF0"
    },
    {
      "Title": "An Extremely Goofy Movie",
      "fulltitle": "An Extremely Goofy Movie (2000)",
      "movie_year": 2000,
      "Categories": "Animation|Comedy|Family|Sport",
      "summary": "It's a big time in Max's life. He's college bound with his friends and finally free of his embarrassing father.",
      "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/An-Extremely-Goofy-Movie-Movie-Poster.jpg",
      "imdb_id": "tt0208185",
      "imdb_rating": 6.4,
      "runtime": 79,
      "language": "English",
      "ytid": "H8oSvldAGfg"
    },
    {
      "Title": "Peter Rabbit",
      "fulltitle": "Peter Rabbit (2018)",
      "movie_year": 2018,
      "Categories": "Adventure|Animation|Comedy|Family|Fantasy",
      "summary": "Based on the books by Beatrix Potter: Peter Rabbit and his three sisters.",
      "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/Peter-Rabbit-Movie-Poster.jpg",
      "imdb_id": "tt5117670",
      "imdb_rating": 6.6,
      "runtime": 95,
      "language": "English",
      "ytid": "7Pa_Weidt08"
    },
    {
      "Title": "Love Songs",
      "fulltitle": "Love Songs (2007)",
      "movie_year": 2007,
      "Categories": "Uncategorized",
      "summary": "Julie's boyfriend Ismaël lives with her; rather than worry about the time he spends with his colleague Alice, Julie invites Alice to join them.",
      "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/Love-Songs-Movie-Poster.jpg",
      "imdb_id": "tt0996605",
      "imdb_rating": 7.2,
      "runtime": 91,
      "language": "English",
      "ytid": "s54vpKAFmS0"
    },
    {
      "Title": 89,
      "fulltitle": "89 (2017)",
      "movie_year": 2017,
      "Categories": "Uncategorized",
      "summary": "89 tells the incredible story of one of football's greatest triumphs.",
      "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/89-Movie-Poster.jpg",
      "imdb_id": "tt7614404",
      "imdb_rating": 8.1,
      "runtime": 91,
      "language": "English",
      "ytid": "5hfAExhHTMM"
    },
    {
      "Title": "The Foster Boy",
      "fulltitle": "The Foster Boy (2011)",
      "movie_year": 2011,
      "Categories": "Drama",
      "summary": "The illegitimate orphan child, 12-year-old Max, is sold by the local minister for a basket of food to the Bösiger family.",
      "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/The-Foster-Boy-Movie-Poster.jpg",
      "imdb_id": "tt2057931",
      "imdb_rating": 7.4,
      "runtime": 107,
      "language": "English",
      "ytid": "E9Qv_XVJ-js"
    }
  ];
  
  export default movies;